import sys

ARGON2_PREHASH_DIGEST_LENGTH = 64
ARGON2_PREHASH_SEED_LENGTH = 72

# Number of synchronization points between lanes per pass
ARGON2_SYNC_POINTS = 4

ARGON2_BLOCK_SIZE = 1024
ARGON2_QWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE // 8
ARGON2_OWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE // 16
ARGON2_HWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE // 32
ARGON2_512BIT_WORDS_IN_BLOCK = ARGON2_BLOCK_SIZE // 64

ARGON2_ADDRESSES_IN_BLOCK = 128

ARGON2_OK = 0

ARGON2_VERSION_10 = 0x10
ARGON2_VERSION_13 = 0x13
ARGON2_VERSION_NUMBER = ARGON2_VERSION_13

ARGON2_MIN_LANES = 1

ARGON2_MAX_LANES = 0xFFFFFF

ARGON2_MIN_THREADS = 1

ARGON2_MAX_THREADS = 0xFFFFFF

ARGON2_MIN_TIME = 1

ARGON2_MAX_TIME = 0xFFFFFFFF

ARGON2_MIN_PWD_LENGTH = 0

ARGON2_MAX_PWD_LENGTH = 0xFFFFFFFF

ARGON2_MIN_AD_LENGTH = 0

ARGON2_MAX_AD_LENGTH = 0xFFFFFFFF

ARGON2_MIN_SALT_LENGTH = 8

ARGON2_MAX_SALT_LENGTH = 0xFFFFFFFF

ARGON2_MIN_SECRET = 0

ARGON2_MAX_SECRET = 0xFFFFFFFF


ARGON2_OUTPUT_PTR_NULL = -1

ARGON2_OUTPUT_TOO_SHORT = -2
ARGON2_OUTPUT_TOO_LONG = -3

ARGON2_PWD_TOO_SHORT = -4
ARGON2_PWD_TOO_LONG = -5

ARGON2_SALT_TOO_SHORT = -6
ARGON2_SALT_TOO_LONG = -7

ARGON2_AD_TOO_SHORT = -8
ARGON2_AD_TOO_LONG = -9

ARGON2_SECRET_TOO_SHORT = -10
ARGON2_SECRET_TOO_LONG = -11

ARGON2_TIME_TOO_SMALL = -12
ARGON2_TIME_TOO_LARGE = -13

ARGON2_MEMORY_TOO_LITTLE = -14
ARGON2_MEMORY_TOO_MUCH = -15

ARGON2_LANES_TOO_FEW = -16
ARGON2_LANES_TOO_MANY = -17

ARGON2_PWD_PTR_MISMATCH = -18
ARGON2_SALT_PTR_MISMATCH = -19
ARGON2_SECRET_PTR_MISMATCH = -20
ARGON2_AD_PTR_MISMATCH = -21

ARGON2_MEMORY_ALLOCATION_ERROR = -22

ARGON2_FREE_MEMORY_CBK_NULL = -23
ARGON2_ALLOCATE_MEMORY_CBK_NULL = -24

ARGON2_INCORRECT_PARAMETER = -25
ARGON2_INCORRECT_TYPE = -26

ARGON2_OUT_PTR_MISMATCH = -27

ARGON2_THREADS_TOO_FEW = -28
ARGON2_THREADS_TOO_MANY = -29

ARGON2_MISSING_ARGS = -30

ARGON2_ENCODING_FAIL = -31

ARGON2_DECODING_FAIL = -32

ARGON2_THREAD_FAIL = -33

ARGON2_DECODING_LENGTH_FAIL = -34

ARGON2_VERIFY_MISMATCH = -35

ARGON2_MIN_MEMORY = 2 * ARGON2_SYNC_POINTS

def argon2_min(a, b):
    return a if a < b else b

ARGON2_MAX_MEMORY_BITS = argon2_min(32, ((sys.maxsize.bit_length() + 1) - 10 - 1))
ARGON2_MAX_MEMORY = argon2_min(0xFFFFFFFF, 1 << ARGON2_MAX_MEMORY_BITS)

ARGON2_DEFAULT_FLAGS = 0

