from randomx.configuration import \
    RANDOMX_FREQ_IADD_RS, \
    RANDOMX_FREQ_IADD_M, \
    RANDOMX_FREQ_ISUB_R, \
    RANDOMX_FREQ_ISUB_M, \
    RANDOMX_FREQ_IMUL_R, \
    RANDOMX_FREQ_IMUL_M, \
    RANDOMX_FREQ_IMULH_R, \
    RANDOMX_FREQ_IMULH_M, \
    RANDOMX_FREQ_ISMULH_R, \
    RANDOMX_FREQ_ISMULH_M, \
    RANDOMX_FREQ_IMUL_RCP, \
    RANDOMX_FREQ_INEG_R, \
    RANDOMX_FREQ_IXOR_R, \
    RANDOMX_FREQ_IXOR_M, \
    RANDOMX_FREQ_IROR_R, \
    RANDOMX_FREQ_IROL_R, \
    RANDOMX_FREQ_ISWAP_R, \
    RANDOMX_FREQ_FSWAP_R, \
    RANDOMX_FREQ_FADD_R, \
    RANDOMX_FREQ_FADD_M, \
    RANDOMX_FREQ_FSUB_R, \
    RANDOMX_FREQ_FSUB_M, \
    RANDOMX_FREQ_FSCAL_R, \
    RANDOMX_FREQ_FMUL_R, \
    RANDOMX_FREQ_FDIV_M, \
    RANDOMX_FREQ_FSQRT_R, \
    RANDOMX_FREQ_CBRANCH, \
    RANDOMX_FREQ_CFROUND, \
    RANDOMX_FREQ_ISTORE, \
    RANDOMX_FREQ_NOP

ceil_NULL = 0
ceil_IADD_RS = ceil_NULL + RANDOMX_FREQ_IADD_RS
ceil_IADD_M = ceil_IADD_RS + RANDOMX_FREQ_IADD_M
ceil_ISUB_R = ceil_IADD_M + RANDOMX_FREQ_ISUB_R
ceil_ISUB_M = ceil_ISUB_R + RANDOMX_FREQ_ISUB_M
ceil_IMUL_R = ceil_ISUB_M + RANDOMX_FREQ_IMUL_R
ceil_IMUL_M = ceil_IMUL_R + RANDOMX_FREQ_IMUL_M
ceil_IMULH_R = ceil_IMUL_M + RANDOMX_FREQ_IMULH_R
ceil_IMULH_M = ceil_IMULH_R + RANDOMX_FREQ_IMULH_M
ceil_ISMULH_R = ceil_IMULH_M + RANDOMX_FREQ_ISMULH_R
ceil_ISMULH_M = ceil_ISMULH_R + RANDOMX_FREQ_ISMULH_M
ceil_IMUL_RCP = ceil_ISMULH_M + RANDOMX_FREQ_IMUL_RCP
ceil_INEG_R = ceil_IMUL_RCP + RANDOMX_FREQ_INEG_R
ceil_IXOR_R = ceil_INEG_R + RANDOMX_FREQ_IXOR_R
ceil_IXOR_M = ceil_IXOR_R + RANDOMX_FREQ_IXOR_M
ceil_IROR_R = ceil_IXOR_M + RANDOMX_FREQ_IROR_R
ceil_IROL_R = ceil_IROR_R + RANDOMX_FREQ_IROL_R
ceil_ISWAP_R = ceil_IROL_R + RANDOMX_FREQ_ISWAP_R
ceil_FSWAP_R = ceil_ISWAP_R + RANDOMX_FREQ_FSWAP_R
ceil_FADD_R = ceil_FSWAP_R + RANDOMX_FREQ_FADD_R
ceil_FADD_M = ceil_FADD_R + RANDOMX_FREQ_FADD_M
ceil_FSUB_R = ceil_FADD_M + RANDOMX_FREQ_FSUB_R
ceil_FSUB_M = ceil_FSUB_R + RANDOMX_FREQ_FSUB_M
ceil_FSCAL_R = ceil_FSUB_M + RANDOMX_FREQ_FSCAL_R
ceil_FMUL_R = ceil_FSCAL_R + RANDOMX_FREQ_FMUL_R
ceil_FDIV_M = ceil_FMUL_R + RANDOMX_FREQ_FDIV_M
ceil_FSQRT_R = ceil_FDIV_M + RANDOMX_FREQ_FSQRT_R
ceil_CBRANCH = ceil_FSQRT_R + RANDOMX_FREQ_CBRANCH
ceil_CFROUND = ceil_CBRANCH + RANDOMX_FREQ_CFROUND
ceil_ISTORE = ceil_CFROUND + RANDOMX_FREQ_ISTORE
ceil_NOP = ceil_ISTORE + RANDOMX_FREQ_NOP

